import json, os, glob, datetime
from pathlib import Path

ROOT       = Path(".")
LEDGER     = ROOT/"docs"/"logs"/"cost-ledger.jsonl"
SAFE_FILE  = ROOT/"ops"/"flags"/"safe-mode.json"
BOOST_FILE = ROOT/"ops"/"flags"/"boost.json"
QUEUE_FILE = ROOT/"ops"/"queue.jsonl"
APPR_DIR   = ROOT/"ops"/"approvals"
RUN_DIR    = ROOT/"docs"/"orchestrator"/"from-agents"/"AGENT-1"
OUT_MD     = ROOT/"docs"/"orchestrator"/"HEALTH.md"

def read_jsonl_sum(path: Path) -> float:
    total = 0.0
    if path.exists():
        for ln in path.read_text(encoding="utf-8").splitlines():
            try:
                d = json.loads(ln); total += float(d.get("usd", 0.0))
            except: pass
    return round(total, 2)

def read_queue_count(path: Path) -> int:
    n = 0
    if path.exists():
        for _ in path.read_text(encoding="utf-8").splitlines():
            n += 1
    return n

def approvals_summary(dirp: Path):
    pending=0; approved=0; total=0
    if dirp.exists():
        for p in dirp.glob("*.json"):
            try:
                d = json.loads(p.read_text(encoding="utf-8")); total += 1
                st = (d.get("status") or "").lower()
                if st == "approved": approved += 1
                elif st == "pending": pending += 1
            except: pass
    return dict(total=total, approved=approved, pending=pending)

def latest_of(pattern: str):
    paths = glob.glob(pattern)
    if not paths: return None
    paths.sort(key=lambda s: os.path.getmtime(s))
    return paths[-1].replace("\\","/")

def main():
    spent = read_jsonl_sum(LEDGER)
    safe_on = SAFE_FILE.exists()
    boost = None
    if BOOST_FILE.exists():
        try: boost = json.loads(BOOST_FILE.read_text(encoding="utf-8")).get("remaining")
        except: boost = None
    qlen = read_queue_count(QUEUE_FILE)
    appr = approvals_summary(APPR_DIR)
    latest_zip = latest_of(str(RUN_DIR/"run-*-attach.zip"))
    latest_log = latest_of(str(RUN_DIR/"run-*.log"))
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%SZ")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(f"""# Orchestrator Health

**As of:** {ts} UTC

## Budget
- **Cap:** $75.00
- **Spent (ledger):** **${spent:.2f}**
- **Mode:** {"ECONOMY" if spent >= 60 else "NORMAL"}  <!-- visual only -->
- **SAFE-MODE:** {"ON" if safe_on else "OFF"}
- **Boost:** {"none" if boost is None else f"${boost:.2f}"}

## Queue
- **Items queued:** {qlen}

## Approvals
- **Total:** {appr['total']}
- **Approved:** {appr['approved']}
- **Pending:** {appr['pending']}

## Latest Agent Artifacts
- **Attach pack:** {latest_zip or "(none)"}  
- **Log:** {latest_log or "(none)"}

---
_This file is generated by `scripts/orchestrator/report_health.py`._
""", encoding="utf-8")

if __name__ == "__main__":
    main()
